<?php
return array('location'=>array(
                'filter'=>array(
                    'status'=>array(
                        'qualified'=>'合格状态',
                        'unqualified'=>'残次状态',
                        'freeze'=>'冻结状态',
                        ),
                    'is_mixed_pro'=>array(
                        '1'=>'是',
                        '2'=>'否'
                        ),
                    'is_mixed_batch'=>array(
                        '1'=>'是',
                        '2'=>'否'
                        )
                    )
                )
            );
