<?php	return array ( 'columns' => array ( 
	'Menu' => array ( 'id' => 'ID', 'name' => '标题', 'link' => '链接', 'order' => '顺序', 'target' => '目标', ), 
	'test' => array ( 'test' => 'test', ), 
	'Log' => array ( 'id' => '', 'operate' => '操作路径', 'ip' => 'IP', 'username' => '用户', 'update_time' => '时间', 'status' => '', ), 
	'Module_table' => array ( 'name' => '名称', 'title' => '标题', 'module' => '模块', 'group' => '分组', 'rows' => '记录', 'data_length' => '数据长度', 'index_length' => '索引大小', 'engine' => '引擎', 'collation' => '字符集', ), 
	'Module_refer' => array ( 'id' => '', 'module' => '参照表名', 'fk' => '参照外键', 'module_refer' => '被参照表', 'pk' => '参照主键', 'condition' => '参照条件', 'refer_type' => '参照类型', 'field_show' => '显示字段', 'limit' => '关联条目', ), 
	'Module' => array ( 'id' => 'ID', 'name' => '名称', ),  
	'Department' => array ( 'id' => 'ID', 'numb' => '编号', 'name' => '名称', 'update_time' => '更新时间', ), 
	'View' => array ( 'name' => '名称', 'column_name' => '名称', 'column_title' => '标题', 'query_able' => '查询', 'list_show' => '显示', 'add_show' => '显示', 'control_type' => '控件类型', 'validate' => '验证条件', ), 
	'User' => array ( 'id' => '', 'username' => '用户名', 'display_name' => '名称', 'email' => 'email', 'register_time' => '注册时间', 'status' => '状态', ), 
	'Role' => array ( 'id' => '', 'name' => '名称', 'numb' => '编号', 'status' => '状态', 'update_time' => '更新时间', 'update_user' => '更新人', ), 
	'Authority' => array ( 'id' => '', 'numb' => '编号', 'name' => '名称', 'url' => 'URL', 'status' => '状态', ), 
	'Group' => array ( 'id' => '', 'numb' => '编号', 'name' => '名称', 'status' => '状态', ), 
	'Parameters' => array ( 'id' => '', 'name' => '名称', 'value' => '值', 'default' => '默认值', 'type' => '类型', 'desc' => '描述', 'status' => '状态', ), 
	'Article' => array ( 'id' => '', 'title' => '标题', 'excerpt' => '摘要', 'content' => '内容', 'author' => '作者', 'author_id' => '作者ID', 'catgory' => '分类', 'post_date' => '发布日期', 'name' => '名称', 'tags' => '标签', 'reference' => '引用地址', 'password' => '密码', 'type' => '文章类型', 'status' => '状态', 'thumbnails' => '缩略图', 'attament' => '附件', 'comment_status' => '评论', 'update_time' => '更新时间', 'lock_type' => '', ), 
	'Backup' => array ( 'id' => '', 'path' => '路径', 'backup_time' => '时间', 'desc' => '描述', 'status' => '状态', ), 
	'Atest' => array ( 'id' => '', 'user_id' => '用户名', 'textbox' => '文本框', 'select' => '列表框', 'datetime' => '日期时间', 'checkbox' => '复选框', 'time' => '时间', ), 
	'Cron' => array ( 'id' => '', 'available' => '', 'type' => '', 'name' => '', 'filename' => '', 'lastrun' => '', 'nextrun' => '', 'weekday' => '', 'day' => '', 'hour' => '', 'minute' => '', ), 
	'User_role' => array ( 'id' => '', 'username' => '用户ID', 'name' => '角色ID', 'status' => '状态', 'update_time' => '更新时间', 'is_deleted' => '', ), 
	'Attachment' => array ( 'id' => '', 'pid' => '', 'type' => '', 'url' => '', 'file_name' => '', 'file_size' => '', 'extension' => '', 'description' => '', 'downloads' => '', ), 
	'Comments' => array ( 'id' => '', 'article_id' => '', 'author' => '', 'email' => '', 'url' => '', 'ip' => '', 'comment_date' => '', 'content' => '', 'approved' => '', 'agent' => '', 'type' => '', 'parent' => '', 'userid' => '', ), 
	'Test' => array ( 'id' => '', 'char20' => 'char20', 'varchar45' => 'varchar45', 'BLOB' => 'BLOB', 'TINYBLOB' => 'TINYBLOB', 'DATE' => 'DAT', 'TIME' => 'TIME', 'DATETIME' => 'DATETIME', 'TIMESTAMP' => 'TIMESPAMP', 'YEAR' => 'YEAR', 'TINYINT' => 'TINYINT', 'SMALLINT' => 'SMALLINT', 'MEDIUMINT' => 'MEDIUMINT', 'INT' => 'INT', 'FLOAT' => 'FLOAT', 'DOUBLE' => 'DOUBLE', 'DECIMAL' => 'DECIMAL', 'BIGINT' => 'BIGINT', 'BIT' => 'BIT', 'ENUMab' => 'ENUMab', 'setabc' => 'setabc', 'LONGTEXT' => 'LONGTEXT', 'MEDIUMTEXT' => 'MEDIUMTEXT', 'TEXT' => 'TEXT', 'TINYTEXT' => 'TINYTEXT', ), 
	'Topic' => array ( 'id' => '', 'views' => '查看次数', 'comments' => '评论次数', 'good' => '赞 次数', 'download' => '下载次数', 'favorite' => '收藏次数', 'share' => '', 'post_date' => '', ), 
	'Numbs' => array ( 'numb' => '号码', 'type' => '类型', 'pool' => '资源池', 'state' => '状态', ), 
	'Company' => array ( 'id' => '', 'name' => '公司名称', 'description' => '公司介绍', 'username' => '用户', 'mobile' => '联系方式', 'adress' => '地址', ), 
	'Task_priority' => array ( 'id' => '', 'name' => '级别', 'value' => '权值', ), 
	'Task_scene' => array ( 'id' => '', 'name' => '情景', ), 
	'Task_project' => array ( 'id' => '', 'name' => '项目', ), 
	'Task' => array ( 'id' => '', 'title' => '任务名称', 'content' => '描述', 'username' => '客户', ), 
	'Task_type' => array ( 'id' => '', 'name' => '名称', ), 
	'Config' => array ( 'id' => '配置ID', 'name' => '配置名称', 'type' => '配置类型', 'title' => '配置说明', 'group' => '配置分组', ), 
	'Payment' => array ( 'id' => '', 'user_id' => '用户', 'account' => '帐户', 'amount' => '金额', 'description' => '备注', ), 
	'Category' => array ( 'id' => '', 'name' => '名称', 'type' => '类型', 'description' => '描述', 'level' => '层级', 'queue' => '顺序', ), 
	'Store' => array ( 'id' => '', 'numb' => '编号', 'name' => '名称', 'location' => '库位', 'type' => '类型', 'spec' => '规格', 'amount' => '数量', 'unit' => '单位', 'in_price' => '进价', 'out_price' => '销售价', 'description' => '备注', 'create_user' => '入库人', 'create_time' => '入库时间', 'status' => '', 'update_user' => '出库人', 'update_time' => '出库时间', ), 
), );?>